### ISSUE TITLE
"Request throttled by server"

### ISSUE THREAD

**Issue by HuXu77** [traversc/getPokeStats#3]
I get this error when running:

`Traceback (most recent call last):
  File "getPokeStats.py", line 25, in <module>
    response = request.call()
  File "/usr/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 182, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/usr/local/lib/python2.7/site-packages/pgoapi/rpc_api.py", line 118, in request
    raise ServerSideRequestThrottlingException("Request throttled by server... slow down man")
pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man`

**Comment by traversc** [comment]
Not sure, since it only calls one function.  Maybe add a sleep in between the log in command and the call.
